name: Deploy Vite (subfolder) to gh-pages
on:
  push:
    branches: [ main ]

permissions:
  contents: write

defaults:
  run:
    working-directory: ./App  # <-- your Vite app lives here

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Debug: confirm the folder and files exist
      - name: Show repo tree
        run: |
          pwd
          ls -la
          echo "---- App dir ----"
          ls -la

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      # Use npm ci if a lockfile exists, otherwise fall back to npm install
      - name: Install deps
        run: |
          if [ -f package-lock.json ]; then
            echo "Using npm ci"
            npm ci
          else
            echo "No package-lock.json found, using npm install"
            npm install
          fi

      - name: Build
        run: npm run build

      - name: Publish to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./App/dist
          cname: psformworks.com
